language: php

sudo: required
dist: trusty

addons:
  chrome: stable

php:
  - 7.2

cache:
  directories:
    - "$HOME/.composer/cache/files"

before_script:
  - travis_retry composer self-update

script:
  - chmod -R 777 bootstrap/cache/ storage/logs/
  - cp .env.testing .env
  - travis_retry composer update --no-interaction --no-progress
  - php artisan key:generate
  - php artisan config:clear
  - php artisan config:cache
  - php artisan migrate --seed
  - php artisan passport:install
  - php artisan storage:link
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve &
  - sleep 5
  - php artisan dusk
  - phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
